[package]
name = "smtp"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
colored = "2"
mio = { version = "0.8", features = ["os-poll", "net"] }
mailparse = "0.13"
chrono = "0.4"

[[bin]]
name = "server"
path = "bin/main.rs"

[profile.release]
lto = "thin"