[package]
name = "smtplib"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
chrono = "0.4"
colored = "2"
fern = "0.6"
log = "0.4"
mailparse = "0.13"
rustls = "0.20"
rustls-pemfile = "0.3"
smol = "1.2"
trust-dns-resolver = "0.20"

[[bin]]
name = "server"
path = "bin/main.rs"

[profile.release]
lto = "thin"